"""Add flashcards and mind map fields to GeneratedContent

Revision ID: 5bd9cdb54a54
Revises: 9a6a36304e8c
Create Date: 2025-10-13 13:41:19.241754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd9cdb54a54'
down_revision = '9a6a36304e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flashcards_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mind_map_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.drop_column('mind_map_json')
        batch_op.drop_column('flashcards_json')

    # ### end Alembic commands ###
