"""Add tables for Stage 3 context and rich content

Revision ID: 6f07ebd4ff6a
Revises: ce89abce0dbb
Create Date: 2025-10-03 13:40:56.998756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f07ebd4ff6a'
down_revision = 'ce89abce0dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_analysis', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('real_world_apps', sa.Text(), nullable=True),
    sa.Column('cultural_connections', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_context_course_id_course')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_context')),
    sa.UniqueConstraint('course_id', name=op.f('uq_course_context_course_id'))
    )
    op.create_table('book_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.Column('complexity_map', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_context_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_context')),
    sa.UniqueConstraint('book_id', name=op.f('uq_book_context_book_id'))
    )
    op.create_table('book_preface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_preface_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_preface')),
    sa.UniqueConstraint('book_id', name=op.f('uq_book_preface_book_id'))
    )
    op.create_table('book_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_summary_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_summary')),
    sa.UniqueConstraint('book_id', name=op.f('uq_book_summary_book_id'))
    )
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rich_html_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.drop_column('rich_html_content')

    op.drop_table('book_summary')
    op.drop_table('book_preface')
    op.drop_table('book_context')
    op.drop_table('course_context')
    # ### end Alembic commands ###
