"""Add subject field to Book model

Revision ID: 9a6a36304e8c
Revises: 3e8cb6c7d5c1
Create Date: 2025-10-13 06:23:01.047276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6a36304e8c'
down_revision = '3e8cb6c7d5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
