"""Add Semester model and link to Book

Revision ID: 9cbf7ac102bd
Revises: 5bd9cdb54a54
Create Date: 2025-10-15 12:28:20.860874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbf7ac102bd'
down_revision = '5bd9cdb54a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_semester_course_id_course')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester'))
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_book_semester_id_semester'), 'semester', ['semester_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_book_semester_id_semester'), type_='foreignkey')
        batch_op.drop_column('semester_id')

    op.drop_table('semester')
    # ### end Alembic commands ###
