"""Change explanation_style to Text

Revision ID: b349e50bf7e1
Revises: dc4f7d5a3c2c
Create Date: 2025-11-01 07:45:18.256001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b349e50bf7e1'
down_revision = 'dc4f7d5a3c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_context', schema=None) as batch_op:
        batch_op.alter_column('explanation_style',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_context', schema=None) as batch_op:
        batch_op.alter_column('explanation_style',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
