"""Initial migration for Stage 2

Revision ID: ce89abce0dbb
Revises:
Create Date: 2025-10-03 13:35:33.357645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce89abce0dbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_course_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    op.create_table('user_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_style', sa.String(length=100), nullable=True),
    sa.Column('academic_level', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('explanation_style', sa.String(length=100), nullable=True),
    sa.Column('generated_context_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_context_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_context')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_context_user_id'))
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('original_name', sa.String(length=150), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_book_course_id_course')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_book_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book'))
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('page_range', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_chapter_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter'))
    )
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_generated_content_chapter_id_chapter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_content')),
    sa.UniqueConstraint('chapter_id', name=op.f('uq_generated_content_chapter_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_content')
    op.drop_table('chapter')
    op.drop_table('book')
    op.drop_table('user_context')
    op.drop_table('course')
    op.drop_table('user')
    # ### end Alembic commands ###
