"""Initial migration for complete application

Revision ID: dc4f7d5a3c2c
Revises:
Create Date: 2025-10-17 05:26:18.335225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4f7d5a3c2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_course_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    op.create_table('user_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_style', sa.String(length=100), nullable=True),
    sa.Column('academic_level', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('explanation_style', sa.String(length=100), nullable=True),
    sa.Column('generated_context_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_context_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_context')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_context_user_id'))
    )
    op.create_table('course_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_analysis', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('real_world_apps', sa.Text(), nullable=True),
    sa.Column('cultural_connections', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_context_course_id_course')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_context')),
    sa.UniqueConstraint('course_id', name=op.f('uq_course_context_course_id'))
    )
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_semester_course_id_course')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester'))
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=150), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('original_name', sa.String(length=150), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_book_course_id_course')),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_book_semester_id_semester')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_book_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book'))
    )
    op.create_table('book_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.Column('complexity_map', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_context_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_context')),
    sa.UniqueConstraint('book_id', name=op.f('uq_book_context_book_id'))
    )
    op.create_table('book_preface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_preface_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_preface')),
    sa.UniqueConstraint('book_id', name=op.f('uq_book_preface_book_id'))
    )
    op.create_table('book_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_summary_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_summary')),
    sa.UniqueConstraint('book_id', name=op.f('uq_book_summary_book_id'))
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('page_range', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_chapter_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter'))
    )
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('rich_html_content', sa.Text(), nullable=True),
    sa.Column('questions_json', sa.Text(), nullable=True),
    sa.Column('flashcards_json', sa.Text(), nullable=True),
    sa.Column('mind_map_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_generated_content_chapter_id_chapter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_content')),
    sa.UniqueConstraint('chapter_id', name=op.f('uq_generated_content_chapter_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_content')
    op.drop_table('chapter')
    op.drop_table('book_summary')
    op.drop_table('book_preface')
    op.drop_table('book_context')
    op.drop_table('book')
    op.drop_table('semester')
    op.drop_table('course_context')
    op.drop_table('user_context')
    op.drop_table('course')
    op.drop_table('user')
    # ### end Alembic commands ###
